CREATE TABLE RIDING_INFO_ALL_TB(
RIDING_INFO_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
YEAR int not null,
MONTH int not null,
BUS_NM varchar(20) not null,
STATION_ID varchar(24) not null,
00시승차총승객수 int,
00시하차총승객수 int,
1시승차총승객수 int,
1시하차총승객수 int,
2시승차총승객수 int,
2시하차총승객수 int,
3시승차총승객수 int,
3시하차총승객수 int,
4시승차총승객수 int,
4시하차총승객수 int,
5시승차총승객수 int,
5시하차총승객수 int,
6시승차총승객수 int,
6시하차총승객수 int,
7시승차총승객수 int,
7시하차총승객수 int,
8시승차총승객수 int,
8시하차총승객수 int,
9시승차총승객수 int,
9시하차총승객수 int,
10시승차총승객수 int,
10시하차총승객수 int,
11시승차총승객수 int,
11시하차총승객수 int,
12시승차총승객수 int,
12시하차총승객수 int,
13시승차총승객수 int,
13시하차총승객수 int,
14시승차총승객수 int,
14시하차총승객수 int,
15시승차총승객수 int,
15시하차총승객수 int,
16시승차총승객수 int,
16시하차총승객수 int,
17시승차총승객수 int,
17시하차총승객수 int,
18시승차총승객수 int,
18시하차총승객수 int,
19시승차총승객수 int,
19시하차총승객수 int,
20시승차총승객수 int,
20시하차총승객수 int,
21시승차총승객수 int,
21시하차총승객수 int,
22시승차총승객수 int,
22시하차총승객수 int,
23시승차총승객수 int,
23시하차총승객수 int
);